######################################################################
# Automatically generated by qmake (3.0) Mon Sep 21 14:06:25 2015
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = a1
INCLUDEPATH += .

# Input
HEADERS += game.h renderer.h window.h
SOURCES += game.cpp main.cpp renderer.cpp window.cpp
